inherit: true

#Copied from https://www.adayinthelifeof.nl/2013/11/20/external-code-coverage-with-travis-scrutinizer/
tools:
    external_code_coverage:
      timeout: 600

filter:
    paths: [tests/*,code/*]
